# Generated by Django 4.2.4 on 2023-08-18 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="image",),
        migrations.RemoveField(model_name="post", name="likes",),
        migrations.AddField(
            model_name="post",
            name="deadline_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="post", name="done", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="return_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
