# Generated by Django 4.2.4 on 2023-08-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_image_remove_post_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.CharField(default="가천대학교", max_length=128),
        ),
    ]
