# Generated by Django 4.2.4 on 2023-08-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_location"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="author", new_name="user",),
    ]
