# Generated by Django 4.2.4 on 2023-08-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_rename_author_post_user"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="user", new_name="author",),
    ]
