# Generated by Django 4.2.4 on 2023-08-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_position_remove_profile_subjects_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="borrow_cnd", new_name="borrow_cnt",
        ),
    ]
