# Generated by Django 4.2.4 on 2023-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_comment_postid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="postid", field=models.IntegerField(),
        ),
    ]
