# Generated by Django 4.2.4 on 2023-08-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_alter_comment_postid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="writer", new_name="user",
        ),
    ]
