# Generated by Django 4.2.4 on 2023-08-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0004_rename_writer_comment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="user", new_name="writer",
        ),
    ]
